# SPDX-License-Identifier: Apache-2.0

test:
  stage: test
  only:
    - branches
    - merge_requests
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache go make
  script:
    - make vet build
